namespace SpriteKind {
    export const tree = SpriteKind.create()
    export const water = SpriteKind.create()
    export const god = SpriteKind.create()
    export const Fairy = SpriteKind.create()
    export const FallenTree = SpriteKind.create()
    export const SpecialTree = SpriteKind.create()
    export const GoldenAxe = SpriteKind.create()
    export const BronzeAxe = SpriteKind.create()
    export const SilverAxe = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.tree, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        heroSprite.x += -10
        if (Math.percentChance(50)) {
            sprite.sayText("砍倒啦", 1000, false)
            otherSprite.setImage(img`
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                .......ee.......
                ......eeee......
                .....eeeeee.....
                .......ee.......
                `)
            otherSprite.setKind(SpriteKind.FallenTree)
            info.changeScoreBy(1)
        } else {
            sprite.sayText("这棵树好大", 1000, false)
        }
    }
})
sprites.onDestroyed(SpriteKind.GoldenAxe, function (sprite) {
    pause(2000)
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.SpecialTree, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        otherSprite.setFlag(SpriteFlag.Ghost, true)
        game.splash("手一滑,斧头飞了")
        heroSprite.setImage(img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            .ffeeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            .ffefbf44fbfeff.........
            ..fe41fddf14ef..........
            ..efeddddddefe..........
            ...ef122221fe...........
            ...4f145541f4...........
            ....ffffffff............
            .....ffffff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
        heroSprite.sayText("呜呜呜呜", 1000, false)
        pause(2000)
        game.splash("泉水里面出现了仙子")
        fairySprite = sprites.create(img`
            . . . . . . 5 . 5 . . . . . . . 
            . . . . . f 5 5 5 f f . . . . . 
            . . . . f 1 5 2 5 1 6 f . . . . 
            . . . f 1 6 6 6 6 6 1 6 f . . . 
            . . . f 6 6 f f f f 6 1 f . . . 
            . . . f 6 f f d d f f 6 f . . . 
            . . f 6 f d f d d f d f 6 f . . 
            . . f 6 f d 3 d d 3 d f 6 f . . 
            . . f 6 6 f d d d d f 6 6 f . . 
            . f 6 6 f 3 f f f f 3 f 6 6 f . 
            . . f f d 3 5 3 3 5 3 d f f . . 
            . . f d d f 3 5 5 3 f d d f . . 
            . . . f f 3 3 3 3 3 3 f f . . . 
            . . . f 3 3 5 3 3 5 3 3 f . . . 
            . . . f f f f f f f f f f . . . 
            . . . . . f f . . f f . . . . . 
            `, SpriteKind.Fairy)
        tiles.placeOnRandomTile(fairySprite, assets.tile`myTile3`)
        fairySprite.sayText("樵夫，你丢失的是这把金灿灿的斧头吗？", 2000, false)
        goldenAxeSprite = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . e . . . . . . . 
            . . . . 1 . . e e . . . . . . . 
            . . . 1 5 1 e e e . . . . . . . 
            . . . 1 5 5 e 1 1 1 1 1 1 1 . . 
            . . . 1 5 e 5 5 5 5 5 5 5 1 . . 
            . . . 1 e 5 5 5 5 5 5 5 5 1 . . 
            . . . . e 5 5 5 5 5 5 5 5 1 . . 
            . . . . e 5 5 5 5 5 5 5 5 1 . . 
            . . . e e 1 5 5 5 5 5 5 5 1 . . 
            . . . e . . 5 5 5 5 5 5 1 . . . 
            . e e e . . . 1 1 5 5 1 . . . . 
            e e e . . . . . . 1 1 . . . . . 
            e e . . . . . . . . . . . . . . 
            e e . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.GoldenAxe)
        tiles.placeOnTile(goldenAxeSprite, tiles.getTileLocation(7, 4))
        scene.cameraFollowSprite(fairySprite)
        pause(2000)
        if (game.ask("是吗？")) {
            heroSprite.sayText("是我的！", 2000, false)
            pause(2000)
            goldenAxeSprite.sayText("你不是我的主人")
            goldenAxeSprite.startEffect(effects.spray, 2000)
            pause(2000)
            game.over(false)
        } else {
            heroSprite.sayText("不是这么好的斧头", 2000, false)
            pause(2000)
            fairySprite.sayText("是这把银闪闪的斧头吗？", 2000, false)
            silverAxeSprite = sprites.create(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . e . . . . . . . 
                . . . . b . . e e . . . . . . . 
                . . . b 1 b e e e . . . . . . . 
                . . . b 1 1 e b b b b b b b . . 
                . . . b 1 e 1 1 1 1 1 1 1 b . . 
                . . . b e 1 1 1 1 1 1 1 1 b . . 
                . . . . e 1 1 1 1 1 1 1 1 b . . 
                . . . . e 1 1 1 1 1 1 1 1 b . . 
                . . . e e b 1 1 1 1 1 1 1 b . . 
                . . . e . . b 1 1 1 1 1 b . . . 
                . e e e . . . b b 1 1 b . . . . 
                e e e . . . . . . b b . . . . . 
                e e . . . . . . . . . . . . . . 
                e e . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.SilverAxe)
            tiles.placeOnTile(silverAxeSprite, tiles.getTileLocation(9, 4))
            scene.cameraFollowSprite(fairySprite)
            pause(2000)
            if (game.ask("是吗？")) {
                heroSprite.sayText("是我的！", 2000, false)
                pause(2000)
                silverAxeSprite.sayText("你不是我的主人")
                silverAxeSprite.startEffect(effects.spray, 2000)
                pause(2000)
                game.over(false)
            } else {
                heroSprite.sayText("不是这么好的斧头", 2000, false)
                pause(2000)
                fairySprite.sayText("樵夫，你丢失的是这把生锈的斧头吗？", 2000, false)
                brozenAxeSprite = sprites.create(img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . e . . . . . . . 
                    . . . . b . . e e . . . . . . . 
                    . . . b f b e e e . . . . . . . 
                    . . . b f f e b b b b b b b . . 
                    . . . b f e f f f f f f f b . . 
                    . . . b e f f f f f f f f b . . 
                    . . . . e f f f f f f f f b . . 
                    . . . . e f f f f f f f f b . . 
                    . . . e e b f f f f f f f b . . 
                    . . . e . . b f f f f f b . . . 
                    . e e e . . . b b f f b . . . . 
                    e e e . . . . . . b b . . . . . 
                    e e . . . . . . . . . . . . . . 
                    e e . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, SpriteKind.BronzeAxe)
                tiles.placeOnTile(brozenAxeSprite, tiles.getTileLocation(8, 4))
                scene.cameraFollowSprite(fairySprite)
                pause(2000)
                if (game.ask("是吗？")) {
                    heroSprite.sayText("嗯，这是我的斧头", 2000, false)
                    pause(2000)
                    fairySprite.sayText("诚实的樵夫，这三把斧头都是你的", 2000, false)
                    goldenAxeSprite.follow(heroSprite)
                    silverAxeSprite.follow(heroSprite)
                    brozenAxeSprite.follow(heroSprite)
                    pause(3000)
                    game.over(true)
                } else {
                    fairySprite.sayText("我这里没有别的斧头了")
                    brozenAxeSprite.destroy(effects.confetti, 2000)
                    pause(2000)
                    game.over(false)
                }
            }
        }
    }
})
sprites.onDestroyed(SpriteKind.SilverAxe, function (sprite) {
    pause(2000)
    game.over(false)
})
let brozenAxeSprite: Sprite = null
let silverAxeSprite: Sprite = null
let goldenAxeSprite: Sprite = null
let fairySprite: Sprite = null
let heroSprite: Sprite = null
tiles.setTilemap(tilemap`level1`)
heroSprite = sprites.create(img`
    ....................................
    .......fff..........................
    ....fffff2f.........................
    ..ffeeeee22ff........e..............
    .ffeeeeee222ff...b..ee..............
    .feeeefffeeeef..bfbeee..............
    .fffffeee2222ef.bffebbbbb...........
    fffe222fffffe2f.bfeffffffb..........
    fffffffffeeefff.befffffffb..........
    fefe44ebbf44eef..fbffffffb..........
    .fee4d4bbfddef...e.bffffb...........
    ..feee4dddddfee.fe..bbfb............
    ...f2222222eeddef.....b.............
    ...f444445e44ddef...................
    ...ffffffffeeeee....................
    ...fff...ff.........................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    ....................................
    `, SpriteKind.Player)
heroSprite.setPosition(10, 10)
scene.cameraFollowSprite(heroSprite)
controller.moveSprite(heroSprite)
let treeSprite = sprites.create(img`
    ......cc66......
    .....c6576c.....
    ....c677576c....
    ....cc677666....
    ...cc6c6667cc...
    ..6c666777cc6c..
    ..c76666766776..
    ..c6777777776c..
    ..cc67777776cc..
    .c67cc76676676c.
    .c777666667777c.
    .c6777777777766.
    .cc7767776776666
    c676cc6766666776
    c777766666677776
    cc7777777777776c
    .c676777677767c.
    ..cc667666766c..
    ...ccc6c66ccc...
    .....cccccc.....
    .......ee.......
    ......eeee......
    .....eeeeee.....
    .......ee.......
    `, SpriteKind.SpecialTree)
tiles.placeOnTile(treeSprite, tiles.getTileLocation(8, 5))
for (let 值 of tiles.getTilesByType(assets.tile`treeTile`)) {
    treeSprite = sprites.create(img`
        ......cc66......
        .....c6576c.....
        ....c677576c....
        ....cc677666....
        ...cc6c6667cc...
        ..6c666777cc6c..
        ..c76666766776..
        ..c6777777776c..
        ..cc67777776cc..
        .c67cc76676676c.
        .c777666667777c.
        .c6777777777766.
        .cc7767776776666
        c676cc6766666776
        c777766666677776
        cc7777777777776c
        .c676777677767c.
        ..cc667666766c..
        ...ccc6c66ccc...
        .....cccccc.....
        .......ee.......
        ......eeee......
        .....eeeeee.....
        .......ee.......
        `, SpriteKind.tree)
    tiles.placeOnTile(treeSprite, 值)
}
